require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WontonsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Wonton. As you add validations to Wonton, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WontonsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all wontons as @wontons" do
      wonton = Wonton.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:wontons)).to eq([wonton])
    end
  end

  describe "GET #show" do
    it "assigns the requested wonton as @wonton" do
      wonton = Wonton.create! valid_attributes
      get :show, {:id => wonton.to_param}, valid_session
      expect(assigns(:wonton)).to eq(wonton)
    end
  end

  describe "GET #new" do
    it "assigns a new wonton as @wonton" do
      get :new, {}, valid_session
      expect(assigns(:wonton)).to be_a_new(Wonton)
    end
  end

  describe "GET #edit" do
    it "assigns the requested wonton as @wonton" do
      wonton = Wonton.create! valid_attributes
      get :edit, {:id => wonton.to_param}, valid_session
      expect(assigns(:wonton)).to eq(wonton)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Wonton" do
        expect {
          post :create, {:wonton => valid_attributes}, valid_session
        }.to change(Wonton, :count).by(1)
      end

      it "assigns a newly created wonton as @wonton" do
        post :create, {:wonton => valid_attributes}, valid_session
        expect(assigns(:wonton)).to be_a(Wonton)
        expect(assigns(:wonton)).to be_persisted
      end

      it "redirects to the created wonton" do
        post :create, {:wonton => valid_attributes}, valid_session
        expect(response).to redirect_to(Wonton.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved wonton as @wonton" do
        post :create, {:wonton => invalid_attributes}, valid_session
        expect(assigns(:wonton)).to be_a_new(Wonton)
      end

      it "re-renders the 'new' template" do
        post :create, {:wonton => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested wonton" do
        wonton = Wonton.create! valid_attributes
        put :update, {:id => wonton.to_param, :wonton => new_attributes}, valid_session
        wonton.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested wonton as @wonton" do
        wonton = Wonton.create! valid_attributes
        put :update, {:id => wonton.to_param, :wonton => valid_attributes}, valid_session
        expect(assigns(:wonton)).to eq(wonton)
      end

      it "redirects to the wonton" do
        wonton = Wonton.create! valid_attributes
        put :update, {:id => wonton.to_param, :wonton => valid_attributes}, valid_session
        expect(response).to redirect_to(wonton)
      end
    end

    context "with invalid params" do
      it "assigns the wonton as @wonton" do
        wonton = Wonton.create! valid_attributes
        put :update, {:id => wonton.to_param, :wonton => invalid_attributes}, valid_session
        expect(assigns(:wonton)).to eq(wonton)
      end

      it "re-renders the 'edit' template" do
        wonton = Wonton.create! valid_attributes
        put :update, {:id => wonton.to_param, :wonton => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested wonton" do
      wonton = Wonton.create! valid_attributes
      expect {
        delete :destroy, {:id => wonton.to_param}, valid_session
      }.to change(Wonton, :count).by(-1)
    end

    it "redirects to the wontons list" do
      wonton = Wonton.create! valid_attributes
      delete :destroy, {:id => wonton.to_param}, valid_session
      expect(response).to redirect_to(wontons_url)
    end
  end

end
